data:
  train_batch_size: 256
  micro_batch_size: 16  # this is also val batch size
  train_files: ~/data/bs17k/train.parquet
  val_files: ~/data/bs17k/val.parquet
  prompt_key: prompt 
  prompt_dict_keys: [content]
  response_key: answer
  response_dict_keys: [content]
  max_length: 1024
  truncation: left
  balance_dp_token: False
  chat_template: null

model:
  partial_pretrain: "Qwen/Qwen2.5-3B-Instruct"
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    cpu_offload: False
    offload_params: False
  external_lib: null
  enable_gradient_checkpointing: False
  trust_remote_code: True

optim:
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.1
  clip_grad: 1.0

trainer:
  default_local_dir: /usr/xtmp/hc387/TinyZero/qwen-3b/sft
  default_hdfs_dir: null # change the hdfs path here
  resume_path: null
  project_name: qwen-bs17k-sft
  experiment_name: test-qwen-3b
  total_epochs: 4
  logger: ['console']
  seed: 1

